stages:
  - build
  - deploy

buildContainer:
  stage: build
  tags:
    - dockerbuilder
  script:
    - docker login -u bot_user -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG .
    - docker image push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    - docker image rm $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  only:
    - deployment

deployOnDockerHost:
  stage: deploy
  only:
    - deployment
  tags:
    - docker1-shell
  script:
    - docker login -u bot_user -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker ps -q --filter "name=fcm-design-support" | grep -q . && docker stop fcm-design-support && docker rm fcm-design-support
    - > 
      docker run 
      -d
      -p 9024:9024
      --restart=always
      --name=fcm-design-support
      --pull=always
      $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
