"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const types_1 = require("./types");
const haus = new types_1.Dataclass("Haus");
const hausInit = new types_1.State("init", haus);
const hausGemalert = new types_1.State("gemalert", haus);
const hausGefliest = new types_1.State("gefliest", haus);
const haus1Init = new types_1.Instance("1", haus, [hausInit]);
const haus1Gemalert = new types_1.Instance("1", haus, [hausGemalert]);
const maler = new types_1.Role("Maler");
const fliesenleger = new types_1.Role("Fliesenleger");
const meier = new types_1.Ressource("Meier", maler, 1);
const schulze = new types_1.Ressource("Schulze", fliesenleger, 1);
const inputSet = new types_1.InputSet([{ state: hausInit, isList: false }]);
const inputSet2 = new types_1.InputSet([{ state: hausGefliest, isList: false }]);
const malern = new types_1.Activity("malern", 1, 1, maler, [inputSet], [hausGemalert]);
const fliesen = new types_1.Activity("fliesen", 1, 1, fliesenleger, [inputSet, inputSet2], [hausGefliest]);
const currentState = new types_1.ProjectState([haus1Init], []);
const objective1 = new types_1.Objective([haus1Gemalert], [], 1);
const goal = new types_1.Goal([objective1]);
const activities = [malern, fliesen];
const ressources = [meier, schulze];
console.log(currentState.possibleActivites(activities, ressources).map(element => element.name));
